name: Demo Testing Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: demo-deploy
  cancel-in-progress: false

jobs:
  test:
    uses: ./.github/workflows/cdk-test.yml

  build-images:
    uses: ./.github/workflows/demo-build.yml
    secrets: inherit

  validate-prod:
    runs-on: ubuntu-latest
    environment: demo
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup CDK Environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-Demo

      - name: Validate CDK Synthesis (Prod Profile)
        run: npm run cdk synth -- --context envType=prod --context stackName=${{ vars.STACK_NAME }}

      - name: Validate Change Set
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[force-deploy]"* ]]; then
            echo "🚨 Force deploy detected - skipping change set validation"
          else
            ./scripts/github/validate-changeset.sh TAK-${{ vars.STACK_NAME }}-CloudTAK
          fi

  deploy-and-test:
    runs-on: ubuntu-latest
    environment: demo
    needs: [validate-prod, build-images]
    outputs:
      cloudtak-tag: ${{ steps.images.outputs.cloudtak-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup CDK Environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-Demo

      - name: Extract Image Tags
        id: images
        run: |
          CLOUDTAK_TAG="${{ needs.build-images.outputs.cloudtak-tag }}"
          echo "cloudtak-tag=$CLOUDTAK_TAG" >> $GITHUB_OUTPUT

      - name: Deploy Demo with Prod Profile
        run: |
          npm run cdk deploy -- \
            --context envType=prod \
            --context stackName=${{ vars.STACK_NAME }} \
            --context usePreBuiltImages=true \
            --context cloudtakImageTag=${{ steps.images.outputs.cloudtak-tag }} \
            --require-approval never

      - name: Wait for Testing Period
        run: sleep ${{ vars.DEMO_TEST_DURATION || '300' }}

      - name: Run Automated Tests
        run: |
          echo "Placeholder for automated tests"
          # TODO: Add health checks and integration tests

  revert-to-dev-test:
    runs-on: ubuntu-latest
    environment: demo
    needs: [deploy-and-test]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup CDK Environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-Demo

      - name: Revert Demo to Dev-Test Profile
        run: |
          npm run cdk deploy -- \
            --context envType=dev-test \
            --context stackName=${{ vars.STACK_NAME }} \
            --context usePreBuiltImages=true \
            --context cloudtakImageTag=${{ needs.deploy-and-test.outputs.cloudtak-tag }} \
            --require-approval never