name: Weekly Upstream Sync

# This workflow automatically syncs with the upstream CloudTAK repository weekly.
# It runs every Saturday at 2AM New Zealand time, creates a sync branch, applies branding, and opens a PR.
# Manual intervention is required if merge conflicts occur.

on:
  schedule:
    - cron: '0 14 * * 6'  # Saturday 2AM NZST (14:00 UTC)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Check sync mode
        run: |
          SYNC_MODE="${{ vars.SYNC_MODE }}"
          case "$SYNC_MODE" in
            "main")
              echo "✅ Sync mode: main branch"
              ;;
            "tag")
              echo "✅ Sync mode: latest version tag"
              ;;
            *)
              echo "⏸️ Sync disabled (SYNC_MODE not set or invalid)"
              exit 0
              ;;
          esac
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with Upstream
        run: |
          SYNC_MODE="${{ vars.SYNC_MODE }}"
          git remote add upstream https://github.com/dfpc-coe/CloudTAK.git || true
          git fetch upstream --tags
          
          # Determine sync target
          case "$SYNC_MODE" in
            "main")
              SYNC_TARGET="upstream/main"
              SYNC_DESC="main branch"
              ;;
            "tag")
              LATEST_TAG=$(git describe --tags --abbrev=0 upstream/main 2>/dev/null || echo "")
              if [ -z "$LATEST_TAG" ]; then
                echo "⚠️ No tags found, falling back to main branch"
                SYNC_TARGET="upstream/main"
                SYNC_DESC="main branch (no tags available)"
              else
                SYNC_TARGET="$LATEST_TAG"
                SYNC_DESC="tag $LATEST_TAG"
              fi
              ;;
          esac
          
          echo "🔄 Syncing with $SYNC_DESC"
          
          # Create sync branch
          SYNC_BRANCH="sync/upstream-$(date +%Y%m%d)"
          git checkout -b "$SYNC_BRANCH"
          
          # Merge upstream changes (no branding applied)
          if git merge "$SYNC_TARGET" --no-edit; then
            echo "✅ Upstream merge successful from $SYNC_DESC"
            echo "📝 Clean upstream code committed (branding applied at build time)"
            
            # Push sync branch
            git push origin "$SYNC_BRANCH"
            
            # Create pull request
            gh pr create \
              --title "Weekly upstream sync from $SYNC_DESC - $(date +%Y-%m-%d)" \
              --body "Automated sync with upstream CloudTAK repository from $SYNC_DESC. Branding will be applied at build time. Please review changes before merging." \
              --head "$SYNC_BRANCH" \
              --base main
          else
            echo "❌ Merge conflicts detected. Manual intervention required."
            git merge --abort
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}