name: Weekly Upstream Sync

# This workflow automatically syncs with the upstream CloudTAK repository weekly.
# It runs every Saturday at 2AM New Zealand time, creates a sync branch, applies branding, and opens a PR.
# Manual intervention is required if merge conflicts occur.

on:
  schedule:
    - cron: '0 14 * * 6'  # Saturday 2AM NZST (14:00 UTC)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-sync-mode:
    runs-on: ubuntu-latest
    outputs:
      should_sync: ${{ steps.check.outputs.should_sync }}
      sync_mode: ${{ steps.check.outputs.sync_mode }}
    steps:
      - name: Check sync mode
        id: check
        run: |
          SYNC_MODE="${{ vars.SYNC_MODE }}"
          case "$SYNC_MODE" in
            "main")
              echo "✅ Sync mode: main branch"
              echo "should_sync=true" >> $GITHUB_OUTPUT
              echo "sync_mode=main" >> $GITHUB_OUTPUT
              ;;
            "tag")
              echo "✅ Sync mode: latest version tag"
              echo "should_sync=true" >> $GITHUB_OUTPUT
              echo "sync_mode=tag" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "⏸️ Sync disabled (SYNC_MODE not set or invalid)"
              echo "should_sync=false" >> $GITHUB_OUTPUT
              ;;
          esac
  
  sync-upstream:
    needs: check-sync-mode
    if: ${{ needs.check-sync-mode.outputs.should_sync == 'true' }}
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with Upstream
        run: |
          SYNC_MODE="${{ needs.check-sync-mode.outputs.sync_mode }}"
          git remote add upstream https://github.com/dfpc-coe/CloudTAK.git || true
          git fetch upstream --tags
          
          # Determine sync target
          case "$SYNC_MODE" in
            "main")
              SYNC_TARGET="upstream/main"
              SYNC_DESC="main branch"
              ;;
            "tag")
              LATEST_TAG=$(git describe --tags --abbrev=0 upstream/main 2>/dev/null || echo "")
              if [ -z "$LATEST_TAG" ]; then
                echo "⚠️ No tags found, falling back to main branch"
                SYNC_TARGET="upstream/main"
                SYNC_DESC="main branch (no tags available)"
              else
                SYNC_TARGET="$LATEST_TAG"
                SYNC_DESC="tag $LATEST_TAG"
              fi
              ;;
          esac
          
          echo "🔄 Syncing with $SYNC_DESC"
          
          # Create sync branch
          SYNC_BRANCH="sync/upstream-$(date +%Y%m%d)"
          git checkout -b "$SYNC_BRANCH"
          
          # Selectively update only api/ and tasks/ folders instead of merging the entire repository
          echo "🔄 Selectively updating api/ and tasks/ folders from $SYNC_DESC"
          git checkout "$SYNC_TARGET" -- api/ tasks/
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "ℹ️ No changes to api/ or tasks/ folders from $SYNC_DESC"
            exit 0
          else
            # Commit the changes
            git commit -m "Update api/ and tasks/ folders from $SYNC_DESC"
            echo "✅ Selective update successful from $SYNC_DESC"
            echo "📝 Only api/ and tasks/ folders updated (branding applied at build time)"
            
            # Push sync branch
            git push origin "$SYNC_BRANCH"
            
            # Create pull request
            gh pr create \
              --title "Weekly upstream sync of api/ and tasks/ from $SYNC_DESC - $(date +%Y-%m-%d)" \
              --body "Automated selective sync of api/ and tasks/ folders from upstream CloudTAK repository ($SYNC_DESC). Branding will be applied at build time. Please review changes before merging." \
              --head "$SYNC_BRANCH" \
              --base main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}